import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import {
  useListTodos,
  useCreateTodo,
  useUpdateTodo,
  useDeleteTodo,
  getListTodosQueryKey,
} from '../api/generated/todos/todos';

/**
 * Everything below — the hooks, the request/response types — is generated by
 * Orval from the FastAPI OpenAPI schema. We never hand-wrote an API call.
 */
export function TodosPage() {
  const queryClient = useQueryClient();
  const [title, setTitle] = useState('');

  // GET /todos
  const { data: todos, isLoading, isError, error } = useListTodos();

  // Re-fetch the list after any mutation succeeds.
  const invalidateList = () =>
    queryClient.invalidateQueries({ queryKey: getListTodosQueryKey() });

  const createTodo = useCreateTodo({ mutation: { onSuccess: invalidateList } });
  const updateTodo = useUpdateTodo({ mutation: { onSuccess: invalidateList } });
  const deleteTodo = useDeleteTodo({ mutation: { onSuccess: invalidateList } });

  const handleAdd = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;
    createTodo.mutate({ data: { title, completed: false } });
    setTitle('');
  };

  return (
    <div>
      <h1>📝 Todos</h1>
      <p style={styles.subtitle}>
        React Query hooks generated by Orval from FastAPI's OpenAPI schema.
      </p>

      <form onSubmit={handleAdd} style={styles.form}>
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="What needs doing?"
          style={styles.input}
        />
        <button type="submit" disabled={createTodo.isPending}>
          {createTodo.isPending ? 'Adding…' : 'Add'}
        </button>
      </form>

      {isLoading && <p>Loading…</p>}
      {isError && (
        <p style={styles.error}>
          Failed to load: {error?.message ?? 'unknown error'}
        </p>
      )}

      <ul style={styles.list}>
        {todos?.map((todo) => (
          <li key={todo.id} style={styles.item}>
            <label style={styles.label}>
              <input
                type="checkbox"
                checked={todo.completed}
                onChange={() =>
                  updateTodo.mutate({
                    todoId: todo.id,
                    data: { completed: !todo.completed },
                  })
                }
              />
              <span
                style={{
                  textDecoration: todo.completed ? 'line-through' : 'none',
                  opacity: todo.completed ? 0.6 : 1,
                }}
              >
                {todo.title}
              </span>
            </label>
            <button
              onClick={() => deleteTodo.mutate({ todoId: todo.id })}
              style={styles.delete}
              aria-label={`Delete ${todo.title}`}
            >
              ✕
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  subtitle: { color: '#666', fontSize: 14, marginTop: -8 },
  form: { display: 'flex', gap: 8, margin: '20px 0' },
  input: { flex: 1, padding: '8px 10px', fontSize: 16 },
  list: { listStyle: 'none', padding: 0, display: 'grid', gap: 8 },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    border: '1px solid #e0e0e0',
    borderRadius: 8,
  },
  label: { display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' },
  delete: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#c00',
    fontSize: 16,
  },
  error: { color: '#c00' },
};
